### ISSUE TITLE
Closed (i.e. killed app) does not trigger events

### ISSUE THREAD

**Issue by Johan-dutoit** [ombori/react-native-search-api#3]
When the app is completely closed, it does not fire any events (from what I can tell) when the app starts up.

Many other packages provide a `getInitial...` function that we can manually call this on startup to get the data.

- https://facebook.github.io/react-native/docs/linking.html#handling-deep-links
- https://github.com/zo0r/react-native-push-notification/blob/master/index.js#L299

Ps.  great package!

**Comment by Danchoys** [comment]
Hi, @Johan-dutoit! Thank you for your feedback :) I have just fixed this bug in [1.2.0](https://github.com/ombori/react-native-search-api/tree/1.2.0). I know it's sort of late, but better late than never =]
